input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
  }

  if ![app] {
    mutate {
      add_field => { "app" => "unknown" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "pidev-logs-%{[app]}-%{+YYYY.MM.dd}"
  }
}
